### PR TITLE
Add recipe that uses the service worker as a notification dispatcher to multiple tabs

### PR DESCRIPTION
**Pull request by marco-c**
I'd need help to choose the name :smile:

### CODE REVIEW

**Comment by darkwing** [comment]
"Notification Dispatcher" ?

**Comment by darkwing** [comment]
Wow, this is simple and wonderful! :)

I have two suggestions:

-  This currently doesn't work in Chrome, so we may want to add a note about that in the demo or in the README

-  It would be awesome to show "feedback" after they click the submit button, like "Now check your other tabs to see the message"

**Comment by darkwing** [comment]
I might also suggest using a `<form>` tag so the user can hit the `ENTER` key to submit the message.

**Comment by digitarald** [comment]
@marco-c I really like it, could be a good use case for apps (and +1 on David's feedback).

**Pull request closed without merging**
