### PR TITLE
Add 'slash' to cache

### PR DESCRIPTION
**Pull request by darkwing**
Reported:  https://twitter.com/hsablonniere/status/667425018779975680

Seems kinda odd, but I guess not.  Could be 'index.php' or something.

Let me know what you think.

### CODE REVIEW

**Comment by darkwing** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1226364

**Comment by digitarald** [comment]
We add a redirect rule on the server as well to avoid duplicate entries and ensure canonical behaviour. What do you think, @darkwing ?

**Comment by darkwing** [comment]
Good point, another PR coming.

**Comment by darkwing** [comment]
Update here:  https://github.com/mozilla/serviceworker-cookbook/pull/126

**Pull request closed without merging**
