### PR TITLE
Include polyfills for startsWith and endsWith

### PR DESCRIPTION
**Pull request by marco-c**
startsWith and endsWith are unavailable on Node 0.12.

### CODE REVIEW

**Comment by digitarald** [comment]
Would it be easier to just replace them with regexp (aka the solution to every problem ;) ), @brendandahl ?

We also should make sure we run tests with 1.2 to catch those use earlier.

**Comment by brendandahl** [comment]
Why do we need to support v.12?

**Comment by digitarald** [comment]
Make it easier for contributors. We don't really depend on 4.x features so it wouldn't make sense to require it, right?

**Comment by darkwing** [comment]
R+, works for me!

**Pull request merged**
