### PR TITLE
Resolve 62 - Allow opening demo in new window

### PR DESCRIPTION
**Pull request by darkwing**
Not sure how I feel about this.  I added a `<button>` so that you can tab to the icon but....I don't know...

### CODE REVIEW

**Comment by digitarald** [comment]
Can you post a screenshot?

**Comment by darkwing** [comment]
screenshot at nov 19 15-16-08

**Comment by brendandahl** [comment]
My initial thought is the icon tells me that clicking on demo opens a new window.

**Comment by darkwing** [comment]
We could make the `a[href]` the link to the "index.html" page but replace that when the do a regular click on the demo link?  That way someone can command-click that link.

**Pull request merged**
