### PR TITLE
Adding common assets for offline strategies recipes

### PR DESCRIPTION
**Pull request by delapuente**
This is the root for all cache strategies recipes. The assets are needed to avoid delays introduced by proxing from other sites.

@marco-c or @potch do you mind to take a quick look?

### CODE REVIEW

**Comment by delapuente** [comment]
This is the complete lists of strategies-related PR so far:

  * [Cache only](https://github.com/mozilla/serviceworker-cookbook/pull/251)
  * [Network or cache](https://github.com/mozilla/serviceworker-cookbook/pull/250)
  * [Cache and update](https://github.com/mozilla/serviceworker-cookbook/pull/252)
  * [Cache, update and refresh](https://github.com/mozilla/serviceworker-cookbook/pull/253)
  * [Offline fallback](https://github.com/mozilla/serviceworker-cookbook/pull/249)

**Comment by delapuente** [comment]
Kind of review I'm looking for is from the usability point of view. Are demos demonstrating each strategy? Is it confusing? Are the annotated sources well commented? Those kind of things mainly.

**Comment by sole** [comment]
Question - what is the license of the images?

I reviewed the five PRs code, I haven't run them but only focused on usability and readability. Left single comments on each line.

**Comment by delapuente** [comment]
The images come from http://lorempixel.com According to them:

> The provided images are for layout purposes and each image we use for this project is released under the creative commons license (CC BY-SA). For more information visit http://creativecommons.org/licenses/
So, if you want to use the images for more than just layouts, you have to double check the license and ask the author. For this we will link to each photographer's flickr page. Furthermore, we assume no liability.

Actually, I'm not totally sure if this is _more than just layouts_ purposes. Since normal use (API examples: https://lorempixel.com/400/400) was not showing the author, I thought it was not necessary I'm wondering now if we should list the authors. Perhaps is better to use another source. What do you think?

**Comment by delapuente** [comment]
Other recipes from the cookbook use the http://lorempixel.com API but I could not use them directly due to the latencies involved but perhaps adding a clarification notice such as "Attributions of the images can be found on lorempixel.com" and asking them directly could help. I'm happy to revert this PR if neccessary.

**Comment by sole** [comment]
hey, I was just curious about the source of the images. I think if you very clearly link where they come from on the README or anywhere prominent, you should be fine. You're using them for layout/demo purposes.

**Comment by sole** [comment]
The attributions section looks like the ideal place for the image credits: https://github.com/mozilla/serviceworker-cookbook/blob/master/README.md#attributions

**Comment by delapuente** [comment]
Done. I pushed the small modification directly to the master branch.

**Pull request merged**
