### PR TITLE
Replacing the chart with the 101 chart

### PR DESCRIPTION
**Pull request by delapuente**
@darkwing I think you did this recipe. Do you mind to review?

### CODE REVIEW

**Comment by marco-c** [comment]
You'd need to replace the screenshots as well (in https://github.com/mozilla/serviceworker-cookbook/blob/master/live-flowchart/README.md).

**Comment by darkwing** [comment]
I didn't create it but works for me! R+

**Comment by darkwing** [comment]
Nice work @delapuente !

**Comment by marco-c** [comment]
I've filed #212 to update the screenshots.

**Pull request merged**
