### PR TITLE
Push notification with clients management recipe

### PR DESCRIPTION
**Pull request by marco-c**
This currently doesn't completely work in Chrome.
Indeed, `clients.openWindow('./push-clients/index.html')` opens `http://localhost:3003/push-clients/index.html` in Firefox, but `http://localhost:3003/push-clients/push-clients/index.html` in Chrome.

https://bugzilla.mozilla.org/show_bug.cgi?id=1222097

### CODE REVIEW

**Comment by digitarald** [comment]
Sounds like Chrome works as expected as the url should relative to the service worker scope? Did you file a bug, @marco-c ?

**Comment by marco-c** [comment]
> Sounds like Chrome works as expected as the url should relative to the service worker scope? Did you file a bug, @marco-c ?

Yes, I mentioned it in the first comment ;)

**Comment by marco-c** [comment]
I've just CCed you on the bug.

**Comment by marco-c** [comment]
The bug should be fixed soon. I've updated the recipe to follow the specs.

**Comment by darkwing** [comment]
I can confirm it's acting as @marco-c has found.

**Pull request merged**
