### PR TITLE
Fix very first request

### PR DESCRIPTION
**Pull request by tuanphpvn**
In the very first request there are no data to serve cache. We need create one.

### CODE REVIEW

**Comment by marco-c** [comment]
@delapuente are you still maintaining serviceworker-cookbook?

**Comment by delapuente** [comment]
Yup. I was on PTO, I'll review it tomorrow. ;)

**Comment by delapuente** [comment]
Hello @tuanphpvn, could you explain what's the motivation for this change? If it is a bug, it's better if you open an issue, first.

**Comment by marco-c** [comment]
Closing for lack of response from the PR author.

**Pull request closed without merging**
