### PR TITLE
Make push recipe servers stateless

### PR DESCRIPTION
**Pull request by marco-c**
Depends on #154.

### CODE REVIEW

**Comment by awalGarg** [comment]
uhh?

On Thu, Dec 3, 2015 at 8:26 PM Mention Bot <notifications@github.com> wrote:

> By analyzing the blame information on this pull request, we identified
> @awalGarg <https://github.com/awalGarg> to be a potential reviewer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/serviceworker-cookbook/pull/160#issuecomment-161663521>
> .
>
-- 
awal

**Comment by marco-c** [comment]
I guess the bot identified you as a reviewer because you modified some of those lines in the 80-lines PR.

**Comment by awalGarg** [comment]
Is it a mozilla specific bot or Github's new "feature"?

**Comment by marco-c** [comment]
It's https://github.com/facebook/mention-bot. Probably @digitarald enabled it for the repo.

**Comment by awalGarg** [comment]
ahh, well, TIL ;)

I would leave an "LGTM" here anyways :P

**Comment by digitarald** [comment]
It's a best effort system and it seems to have caught the one who knows most about the changeset. It could be more inviting though to review and leave the blaming out ;)

**Pull request merged**
