### PR TITLE
List recipes in order of difficulty

### PR DESCRIPTION
**Pull request by marco-c**
Depends on #89.

### CODE REVIEW

**Comment by darkwing** [comment]
This is an awesome idea.  I think we need some sort of indicator before we merge this though.  What about something like this?  

notification

Maybe only on the first one of each difficulty?  I can code that up, just sounding out thoughts.

**Comment by darkwing** [comment]
Actually we should probably just have "Beginner", "Intermediate", and "Advanced" headers and three separate lists.  That would probably be easiest

**Comment by marco-c** [comment]
My idea was to redesign the list after doing this and after #92, to clearly separate recipes belonging to different categories.

**Comment by marco-c** [comment]
So something like:
```
Category 1
Beginner Recipe 1
Beginner Recipe 2
Intermediate Recipe

Category 2
Beginner Recipe
Intermediate Recipe
Advanced Recipe
```

I don't know if we should also clearly indicate which ones are easy and which more difficult, because it could make the interface too cluttered.

**Comment by darkwing** [comment]
I was thinking we'd do:

```
Beginner
- Recipe 1
- Recipe 2
...

Intermediate
- Recipe 1
- Recipe 2
...
```

**Comment by digitarald** [comment]
the usual chili spiciness color coding might work here, green, yellow, red? I would rather see top level categories for use cases (offline vs push)

**Comment by shidhincr** [comment]
+1

**Comment by marco-c** [comment]
sidebar

**Comment by darkwing** [comment]
R+, this looks good!

**Pull request merged**
